"""remove user password hash

Revision ID: 99767f0b7323
Revises: f354c16478cf
Create Date: 2026-05-19 14:30:09.144185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99767f0b7323'
down_revision: Union[str, Sequence[str], None] = 'f354c16478cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
